version: "1"
services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    command: mongod
    ports:
      - "27017:27017"
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/src
    environment:
      FLASK_ENV: development
      FLASK_APP: ./src/app.py
