version: "1"
services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    command: mongod
    environment:
      MONGO_INITDB_DATABASE: datagran
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - ./data/db
    ports:
      - "27017:27017"
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/src
    environment:
      FLASK_ENV: development
      FLASK_APP: ./src/app.py
