version: "3.8"
services:
  mongo:
    image: "mongo:latest"
    ports:
     - "27017:27017"
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/src
    environment:
      FLASK_ENV: development
      FLASK_APP: ./src/app.py
      FLASK_RUN_HOST: 0.0.0.0